volumes:
  nextcloud:
  db:

networks:
  default:
  pihole_default:
    external: true
  nginx_default:
    external: true

services:
  db:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOT_PASSWD}
      - MYSQL_PASSWORD=${PASSWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${USER}
    networks:
      - default

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - type: tmpfs
        target: /tmp:exec
      - nextcloud:/var/www/html
      - ${HOME}/docker/scripts/servername.conf:/etc/apache2/conf-enabled/servername.conf
    environment:
      - MYSQL_PASSWORD=${PASSWD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=${USER}
      - MYSQL_HOST=db
      - PHP_UPLOAD_LIMIT=512M
      - PHP_MEMORY_LIMIT=1G
    networks:
      - default
      - pihole_default
      - nginx_default
    dns:
      - 172.21.0.2