services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ${HOME}/docker/mullvad_wireguard:/config
      - /lib/modules:/lib/modules
    networks:
      default:
        ipv4_address: 172.30.0.50
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - 8888:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - WEBUI_PORT=8080

    volumes:
    - ${HOME}/qbit/config:/config
    - ${HOME}/Downloads:/downloads #optional
    restart: unless-stopped

networks:
  default:
    name: wgnet
    external: true